server_db:
  mysql_db_name: ltms
  mysql_host: 172.17.0.1
  mysql_port: 3306
  mysql_username: root
  mysql_password: '123456'

http_server:
  http_server_host: 0.0.0.0
  http_server_port: 9082
  http_server_data_dir: /data/datasets

rpc_server:
  rpc_server_host: 0.0.0.0
  rpc_server_port: 9332

client:
  master_url:localhost:9332